name: CVTrade
main: org.cubeville.trade.bukkit.TradePlugin
version: 1.1.2
author: mciolkosz
api-version: "1.21"
depend: [WorldEdit,WorldGuard]
softdepend: [Multiverse-Core]

commands:
  tradeadmin:
    description: Administrative command
    permission: cvtrade.tradeadmin

permissions:
  cvtrade.tradeadmin:
    description: Ability to use the /tradeadmin command
    default: op
